### ISSUE TITLE
Support SearchParameter with ".extension()" in expression

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-search-es#132]
**Describe the bug**
When I try to make an extension field searchable, I got an error "Unexpected "(". Instead, I was expecting to see one of the following:" Here is the [official example](https://www.hl7.org/fhir/R4/searchparameter-example-extension.json.html) regarding SearchParameter on Extension

**To Reproduce**
1. Create file /implementationGuides/example/SearchParameter.json with [official example](https://www.hl7.org/fhir/R4/searchparameter-example-extension.json.html) 
2. Create /impementationGuides/example/.index.json with content:
```
{
  "index-version": 1,
  "files": [
    {
      "filename": "SearchParameter.json",
      "resourceType": "SearchParameter",
      "id": "CustomSearchParameter",
      "url": "http://fhir.example.com/SearchParameter/CustomSearchParameter",
      "version": "1.0.0",
      "type": "reference"
    }
  ]
}
```
3. run command `yarn run compile-igs`

**Expected behavior**
Compile igs without any errors.

**Versions:**
 -  v2.2.0-smart

**Comment by carvantes** [comment]
Hi @Lin-002,  

The issue is with the FHIRPath expression:
```
DocumentReference.extension('http://example.org/fhir/StructureDefinition/participation-agreement')
```
Specifically, we don't support the [.extension() function](https://www.hl7.org/fhir/fhirpath.html#functions).

The workaround is to use the `.extension.where(url = string)` syntax instead. (`.extension()` is just a syntactical shortcut) i.e.
```
DocumentReference.extension.where(url = 'http://example.org/fhir/StructureDefinition/participation-agreement')
```

We'll evaluate supporting the `.extension()` function, but given that there's a simple workaround it is unlikely to be prioritized soon.
Also the IGs we've seen all use the `.extension.where(url = string)`. Maybe that gives better compatibility since `.extension()` is not truly part of the base [FHIRPath spec](https://hl7.org/fhirpath/), but rather functionality added by FHIR.

Thanks for reporting the issue!

---

Some more context: [FHIRPath](https://hl7.org/fhirpath/) as a whole has some very complex constructs (e.g. projection functions, tree navigation functions, etc.), but search parameters definitions tend to only use a limited set of simple FHIRPath constructs. Our implementation only understands a subset of FHIRPath that is enough to understand most search parameters.

We've tested our implementation with the following IGs

1. US Core (hl7.fhir.us.core)
2. CARIN Blue Button (hl7.fhir.us.carin-bb)
3. Payer Data Exchange (hl7.fhir.us.davinci-pdex)
4. DaVinci Payer Data Exchange US Drug Formulary(hl7.fhir.us.Davinci-drug-formulary)
5. DaVinci PDEX Plan Net (hl7.fhir.us.davinci-pdex-plan-net)

Search parameters outside those IGs are likely to work, but there may be some that use complex FHIRPath syntax that are not supported.

**Comment by lquanx** [comment]
Thanks very much. I will try out `where`

**Comment by carvantes** [comment]
Hi, 

We released support for the `.extension()` function on `fhir-works-on-aws-search-es@3.9.0`.

In the end it was not such a big change and we think that it is very helpfup for customers that are looking at the official FHIR examples and want to craft their own search parameters.

Although if you are already using the `.extension.where(url = string)` syntax, it is probably better to to keep it that way. Seeing that major IGs use that syntax and that `.extension()` is not in the base FHIRPath spec, leads us to think that the `.extension.where(url = string)` syntax has less compatibility issues with FHIR tools out there (although we haven't validated this).
