### ISSUE TITLE
[Bug] revInclude on a resource only returns a max of 10 records

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-search-es#154]
**Describe the bug**
When running a revInclude for Provenance on a MedicationRequest Resource it is only returning 10 provenance records when there are more than that tied to it.

**To Reproduce**
Example:
https://{{API_URL}}/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/MedicationRequest?patient=Patient/cc8d11df-2df0-4c0a-b478-8169a9228ae3&intent=order&_revinclude=Provenance:target&_count=20

**Expected behavior**
The expectation is that it would return all provenance records for the MedicationRequest resource.

**Comment by ssvegaraju** [comment]
Hi @medhost-gkersting,
I was working on finding where this bug was happening, but noticed this morning that the query above (which had correctly reproduced the bug before) was working correctly. I just wanted to check in with you to see if this was still an issue you were experiencing?

Thanks for your time,
Sukeerth

**Comment by ghost** [comment]
@ssvegaraju We will need to pull in some of the latest changes and see if we can still reproduce the issue.

**Comment by ssvegaraju** [comment]
Hi @medhost-gkersting, 
Just wanted to update you on this and let you know that we have merged a fix into mainline for this bug, and it should be available with search-es package v3.9.3 shortly. Thanks again for bringing it to our attention! I'll go ahead and close the issue for now, but feel free to reopen if needed.

Best,
Sukeerth
