### ISSUE TITLE
Searching with a valid search parameter but an invalid value; should return 400

### ISSUE THREAD

**Issue by emilhdiaz** [awslabs/fhir-works-on-aws-search-es#47]
According to the Aegis Touchstone test suites, searching by an invalid search parameter should return an HTTP 400

![Screen Shot 2021-02-17 at 3 32 06 AM](https://user-images.githubusercontent.com/2886234/108177437-3f746300-70d1-11eb-9f73-b314a1935852.png)

**Comment by nguyen102** [comment]
Ah, yes. Thank you for calling this out Emil. Currently we're doing a string match when searching for date values, which is why this occurs. We need to update our code to fully support searching by dates. I'll add this Bug to our backlog.

By the way, what version of FWoA are you running? When I ran the code from [this version](https://github.com/awslabs/fhir-works-on-aws-deployment/commit/72f4fa23feb68456a924a013dd064beaf75f1b41), with an invalid `_lastUpdated` search param it responds with a 200 HTTP status.

**Comment by emilhdiaz** [comment]
Hi @nguyen102 we're using an alternate deployment repo, so unfortunately I can't point directly to a link that shows all the versions, but here they are (on the left are our tags, on the right your tags/commit hashes): 

```
fhir-works-on-aws-interface 21.2.1 -> v7.1.0
fhir-works-on-aws-routing 21.2.1 -> v4.0.3
fhir-works-on-aws-authz-smart 21.2.1 -> v0.1.2
fhir-works-on-aws-persistence-ddb 21.2.2 -> v3.2.1
fhir-works-on-aws-search-es 21.2.2 -> v2.1.0
```

We also have a slightly different implementation of the the `SMARTHandler`, it's possible that this 403 HTTP status is coming from that code instead of the search service. I can track that down further, if you think the expected behavior here is a non-error response from the search service.

**Comment by nguyen102** [comment]
Looks like you have the latest released version of search service. And yep, I can confirm that no error is thrown by search service when an invalid search parameter value is provided.

**Comment by emilhdiaz** [comment]
@nguyen102 looks like this other issue is related if not the same: https://github.com/awslabs/fhir-works-on-aws-search-es/issues/17

Does this mean that the ES service should return a 400 now instead?

**Comment by nguyen102** [comment]
Ah that issue is slightly different. Search will return a 400 if we're trying to search on a field that doesn't exist. For example if we search `?foo=1234` that will throw an error. In this case though, we're searching on an invalid date value for a valid search parameter (`?_lastUpdated=foo`), which will return in a 200 (with no results).
